### ISSUE TITLE
Concurrency issue while hosting in a cluster

### ISSUE THREAD

**Issue by kevinlyk** [Chinchilla-Software-Com/CQRS#129]
AggregateRoot are applying changes with the same version number. Suspect root cause is due to us hosting in a service fabric and thus the ReaderWriterLockSlim is not shared among the clusters. Might need to use a distributed lock if that's the case?

**Comment by cdmdotnet** [comment]
You are correct in that the base modules of CQRS.NET do not handle aggregate root concurrency gracefully - the EventStore throws an exception to protect itself if the unique indexes are correct as a last resort. We didn't want to solve the problem of concurrency by building yet another concurrency control framework... that's not what our skills are best applied to. Also we didn't want to add unnecessary complexity to the core modules for those that don't have that issue. Instead we allow developers to pick a concurrency framework of their own choosing that suits their requirements. To date we have the Akka.NET modules to provide this... however you can choose to use any framework of choice such as something from [Micrsosoft](https://dotnet.github.io/orleans/). Be aware though that this still won't deal with concurrency from a user perspective. All these libraries will do is re-queue the work so they execute one after the other... but nothing at this level ensures that between the time a users loads some data on-screen and finally presses save to send their changes to the API, that the aggregate root hasn't been modified by some other user. These concurrency frameworks simply enforce traditional "Last man wins" without too much erroring. Ensuring true concurrency (from the user perspective rather than a machine perspective) is a much deeper issue. If you don't need that level of security and data integrity then the Akka.NET CQRS modules should work for you... although they add a bit of complexity given their internal networking nature. There are a few tests for the Akka.NET modules which might help you understand how to develop with that module... our documentation on that specific topic is rather light as few people have truely had that level of concurrency to deal with.
